docs/AboutUs.md
=> changed about me (si thu)

docs/AboutUs.md
=> change AboutUs page (Nathan)

docs/AboutUs.md
=> update AboutUs Lam Hoi Kei

src/main/java/seedu/planpal/contacts/ContactManager.java, src/main/java/seedu/planpal/utility/Parser.java
Tasks done:
completed edit functionality for v1.0
=> Add EditContact

src/main/java/seedu/planpal/contacts/Contact.java, src/main/java/seedu/planpal/contacts/ContactManager.java, src/main/java/seedu/planpal/utility/Editable.java, src/main/java/seedu/planpal/utility/Functions.java, src/main/java/seedu/planpal/utility/Parser.java
Update edit function such that it is scalable to other lists
=> Gavin chua edit contacts2

src/main/java/seedu/planpal/contacts/Contact.java
Update the add function to incorporate the edit function
=> Add function (updated)

src/main/java/seedu/planpal/PlanPal.java, src/main/java/seedu/planpal/utility/FileManager.java, src/main/java/seedu/planpal/utility/Parser.java, text-ui-test/EXPECTED.TXT
implement loading and saving contact in contacts.txt inside data directory for add and edit commands
=> File management

src/main/java/seedu/planpal/contacts/Contact.java, src/main/java/seedu/planpal/contacts/ContactManager.java, src/main/java/seedu/planpal/utility/Functions.java, src/test/java/seedu/planpal/contacts/ContactManagerTest.java
Add Junit tests for Editing of contact
=> Add JUnit tests

.gitignore, data/contacts.txt, src/main/java/seedu/planpal/PlanPal.java, src/main/java/seedu/planpal/contacts/Contact.java, src/main/java/seedu/planpal/contacts/ContactManager.java, src/main/java/seedu/planpal/utility/Functions.java, src/main/java/seedu/planpal/utility/Parser.java, src/main/java/seedu/planpal/utility/filemanager/FileManager.java, src/main/java/seedu/planpal/utility/filemanager/Storeable.java, src/test/java/seedu/planpal/contacts/ContactManagerTest.java, src/test/java/seedu/planpal/contacts/EditFunctionTest.java, text-ui-test/EXPECTED.TXT
Added JUnit Tests for add-function
=> Add-function-unit-testing

META-INF/MANIFEST.MF, src/main/java/seedu/planpal/utility/filemanager/FileManager.java
specifically, debug the case when list is empty
=> debug save function

build.gradle, src/main/java/seedu/planpal/AssertionTest.java, src/main/java/seedu/planpal/PlanPal.java, src/main/java/seedu/planpal/contacts/Contact.java, src/main/java/seedu/planpal/contacts/ContactManager.java, src/main/java/seedu/planpal/utility/ListFunctions.java, src/main/java/seedu/planpal/utility/Parser.java, src/main/java/seedu/planpal/utility/Ui.java, src/main/java/seedu/planpal/utility/filemanager/FileManager.java
Complete my assertion and logging task for week 9
=> Assertion and logging

src/main/java/seedu/planpal/contacts/ContactManager.java, src/main/java/seedu/planpal/utility/ListFunctions.java
Assertions are done in ListFunctions.java and ContactManager.java 
Logging is done in ContactManager.java
=> Assertions and logging done for delete contact function

src/main/java/seedu/planpal/contacts/Contact.java, src/main/java/seedu/planpal/contacts/ContactManager.java, src/test/java/seedu/planpal/contacts/ContactManagerTest.java
Allow more fields in Contact ("name", "phoneNumber", "email")
update test
refactor code for improved neatness and readability in category information editing.
=> Contact extension

src/main/java/seedu/planpal/PlanPal.java, src/main/java/seedu/planpal/contacts/Contact.java, src/main/java/seedu/planpal/contacts/ContactManager.java, src/main/java/seedu/planpal/expenses/Expense.java, src/main/java/seedu/planpal/expenses/ExpenseManager.java, src/main/java/seedu/planpal/utility/ListFunctions.java, src/main/java/seedu/planpal/utility/Parser.java, src/main/java/seedu/planpal/utility/Ui.java, src/main/java/seedu/planpal/utility/filemanager/FileManager.java, src/main/java/seedu/planpal/utility/filemanager/Storeable.java, src/main/java/seedu/planpal/utility/parser/ContactParser.java, src/main/java/seedu/planpal/utility/parser/ExpenseParser.java, src/main/java/seedu/planpal/utility/parser/Parser.java, src/main/java/seedu/planpal/utility/parser/ParserFactory.java, src/test/java/seedu/planpal/contacts/ContactManagerTest.java, text-ui-test/EXPECTED.TXT
Key changes:
1. refactored file management codes
2. refactored parser class
3. added expense tracker
4. added modes
=> Expense tracker

src/main/java/seedu/planpal/contacts/Contact.java, src/main/java/seedu/planpal/contacts/ContactManager.java, src/main/java/seedu/planpal/utility/Ui.java, src/main/java/seedu/planpal/utility/parser/ContactParser.java, src/main/java/seedu/planpal/utility/parser/Parser.java
1. add category
2. remove category
3. search contacts of a category
4. edit categories of a contact
5. view categories
=> Basic functions of category is added

src/main/java/seedu/planpal/activities/Activity.java, src/main/java/seedu/planpal/activities/ActivityManager.java, src/main/java/seedu/planpal/utility/parser/ActivityParser.java, src/main/java/seedu/planpal/utility/parser/Parser.java, src/main/java/seedu/planpal/utility/parser/ParserFactory.java
new activity list done. add activities method is also included.
=> Add activities method 

src/main/java/seedu/planpal/activities/ActivityManager.java, src/main/java/seedu/planpal/utility/parser/ActivityParser.java
added in delete activities method, removed logging but assertion line remained.
=> Delete activities method

docs/DeveloperGuide.md, src/main/java/seedu/planpal/utility/Ui.java, text-ui-test/EXPECTED.TXT
add lines to dg and edit printing of the modes to include activities
=> add lines to dg and update the printMode function

src/main/java/seedu/planpal/activities/Activity.java
Reformatted the activity list to include activityType as well.
=> Add activities function to include activityType

src/main/java/seedu/planpal/activities/ActivityManager.java, src/main/java/seedu/planpal/utility/parser/Parser.java
Currently only Edit function for Activity does not work properly
=> Edit Activity class

docs/team/crystal-bys.md
=> add PPP-YS

src/main/java/seedu/planpal/modes/expenses/Expense.java, src/main/java/seedu/planpal/modes/expenses/ExpenseManager.java, src/main/java/seedu/planpal/utility/Ui.java, src/main/java/seedu/planpal/utility/filemanager/FileManager.java, src/main/java/seedu/planpal/utility/parser/ExpenseParser.java, src/main/java/seedu/planpal/utility/parser/Parser.java, src/main/java/seedu/planpal/utility/parser/ParserFactory.java, src/main/java/seedu/planpal/utility/parser/modeparsers/ActivityParser.java, src/main/java/seedu/planpal/utility/parser/modeparsers/ContactParser.java, src/main/java/seedu/planpal/utility/parser/modeparsers/ExpenseParser.java
Key changes made:
1. loading of files now handles corruption and pinpoints the first instance that commands stopped execution.
2. budget setting is now available
3. editing of expenses can now be done
4. values can now be saved using the fileManager class
5. exceptions throw now no longer loops the whole program back to the mode selection page.
6. Ui now contains code to send outputs into dummy stream.
=> Budget function

src/main/java/seedu/planpal/exceptions/expenses/NoBudgetException.java, src/main/java/seedu/planpal/modes/activities/Activity.java, src/main/java/seedu/planpal/modes/contacts/Contact.java, src/main/java/seedu/planpal/modes/expenses/Expense.java, src/main/java/seedu/planpal/modes/expenses/ExpenseManager.java, src/main/java/seedu/planpal/utility/ListFunctions.java, src/main/java/seedu/planpal/utility/filemanager/FileManager.java, src/main/java/seedu/planpal/utility/parser/Parser.java, src/main/java/seedu/planpal/utility/parser/ParserFactory.java, src/main/java/seedu/planpal/utility/parser/modeparsers/ExpenseParser.java, src/test/java/seedu/planpal/expenses/AddExpenseTest.java, src/test/java/seedu/planpal/expenses/DeleteExpenseTest.java
add function to allow multiple budgets and expenses by month
=> Expenses monthly edition

.gitignore, build.gradle, src/main/java/seedu/planpal/modes/activities/Activity.java, src/main/java/seedu/planpal/modes/contacts/Contact.java, src/main/java/seedu/planpal/modes/contacts/SetContactCategory.java, src/main/java/seedu/planpal/modes/expenses/Expense.java, src/main/java/seedu/planpal/modes/expenses/ExpenseManager.java, src/main/java/seedu/planpal/modes/expenses/ExpenseModeFunctions.java, src/main/java/seedu/planpal/modes/expenses/RecurringExpense.java, src/main/java/seedu/planpal/modes/expenses/managers/BudgetManager.java, src/main/java/seedu/planpal/modes/expenses/managers/ExpenseManager.java, src/main/java/seedu/planpal/modes/expenses/managers/RecurringManager.java, src/main/java/seedu/planpal/utility/ListFunctions.java, src/main/java/seedu/planpal/utility/Ui.java, src/main/java/seedu/planpal/utility/filemanager/BackUpManager.java, src/main/java/seedu/planpal/utility/filemanager/FileManager.java, src/main/java/seedu/planpal/utility/parser/Parser.java, src/main/java/seedu/planpal/utility/parser/ParserFactory.java, src/main/java/seedu/planpal/utility/parser/modeparsers/ActivityParser.java, src/main/java/seedu/planpal/utility/parser/modeparsers/ContactParser.java, src/main/java/seedu/planpal/utility/parser/modeparsers/ExpenseParser.java, src/test/java/seedu/planpal/contacts/ContactManagerTest.java, src/test/java/seedu/planpal/expenses/AddExpenseTest.java, src/test/java/seedu/planpal/expenses/DeleteExpenseTest.java, src/test/java/seedu/planpal/expenses/EditExpenseTest.java, src/test/java/seedu/planpal/expenses/FindExpenseTest.java, src/test/java/seedu/planpal/expenses/SetBudgetTest.java, src/test/java/seedu/planpal/expenses/ViewExpenseListTest.java
1. add function to save backups in a zip folder.
2. Made some changes to the ui to make it more useable.
3. Added functionality to use recurring expenses
4. recurring expenses work like a list
=> Recurring expense

docs/UserGuide.md, src/main/java/seedu/planpal/modes/activities/Activity.java
Fixed checkstyle error from earlier PR.
=> Debug activity

docs/DeveloperGuide.md, docs/UserGuide.md
trying to change the ug table format issue
=> C2 UG change

docs/UserGuide.md
=> debug ug breaking of tables

docs/DeveloperGuide.md
=> added TOC for DG

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/planpal/modes/contacts/Contact.java, src/main/java/seedu/planpal/modes/contacts/SetContactCategory.java, src/main/java/seedu/planpal/utility/Ui.java, src/main/java/seedu/planpal/utility/parser/modeparsers/ContactParser.java, src/test/java/seedu/planpal/contacts/ContactManagerTest.java
implemented to throw exception when adding contact with empty name
implemented to throw exception when adding contact with invalid email
add to UG the information about email format
=> Fixed contact issue

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/planpal/modes/contacts/SetContactCategory.java, src/main/java/seedu/planpal/utility/Ui.java, src/main/java/seedu/planpal/utility/parser/modeparsers/ContactParser.java, src/test/java/seedu/planpal/contacts/ContactManagerTest.java
update Ui to show when inside setting category mode clearly
update Ui to show when exiting setting category mode clearly
Change command from 'quit' to 'exit' to exit setting category mode to enhance consistency
=> Fix contact category issues

src/main/java/seedu/planpal/modes/expenses/managers/BudgetManager.java
debug issue where changing budget file name corrupts all data
=> debug issue where changing budget file name corrupts all data

src/main/java/seedu/planpal/modes/activities/Activity.java, src/main/java/seedu/planpal/modes/contacts/Contact.java, src/main/java/seedu/planpal/modes/expenses/Expense.java, src/main/java/seedu/planpal/modes/expenses/ExpenseModeFunctions.java, src/main/java/seedu/planpal/modes/expenses/managers/RecurringManager.java, src/main/java/seedu/planpal/utility/ListFunctions.java, src/main/java/seedu/planpal/utility/parser/modeparsers/ActivityParser.java, src/main/java/seedu/planpal/utility/parser/modeparsers/ContactParser.java, src/main/java/seedu/planpal/utility/parser/modeparsers/ExpenseParser.java
made changes to allow for case sensative words. did not update ug.
=> Handle issues

src/main/java/seedu/planpal/modes/expenses/managers/RecurringManager.java
debug recurring to allowing adding of recurring into current month if the current month is newly created
=> recurring is debugged to work for current month if current month is new

src/test/java/seedu/planpal/storage/BackUpManagerTest.java
add test cases for backup and restore function
=> test cases added for restore and backup functions
